name: submission_awal_flutter_fundamental
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  flutter_native_splash: 2.4.1
  dio: ^5.7.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.8
  focus_detector: ^2.0.1
  sqflite: ^2.4.0
  shared_preferences: ^2.3.2
  android_alarm_manager_plus: ^4.0.4
  flutter_local_notifications: ^17.2.3
  rxdart: ^0.28.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/restaurant.json
    - images/

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: images/splash.png
  color: "#FFFFFF"
  android_12:
    image: images/splash.png
    color: "#FFFFFF"